CREATE TABLE `musicbotdb`.`SONG` (
  `URL` VARCHAR(255) NOT NULL,
  `TITLE` VARCHAR(255) NULL,
  `PLAY_COUNT` INT UNSIGNED NULL,
  `VOLUME` DECIMAL(3,2) UNSIGNED NULL,
  `UPDT_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`URL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
DELIMITER $$
USE `musicbotdb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musicbotdb`.`SONG_AFTER_DELETE` AFTER DELETE ON `SONG` FOR EACH ROW
BEGIN
    DELETE FROM `musicbotdb`.`USER_SONG` WHERE `URL` = OLD.URL;
    DELETE FROM `musicbotdb`.`MOOD_SONG` WHERE `URL` = OLD.URL;
END$$
DELIMITER ;

CREATE TABLE `musicbotdb`.`MOOD` (
  `TAG` VARCHAR(45) NOT NULL,
  `UPDT_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAG`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
DELIMITER $$
USE `musicbotdb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musicbotdb`.`MOOD_AFTER_DELETE` AFTER DELETE ON `MOOD` FOR EACH ROW
BEGIN
    DELETE FROM `MOOD_SONG` WHERE `MOOD_SONG`.`TAG` = `OLD`.`TAG`;
    UPDATE `USER` SET `USER`.`TAG` = NULL WHERE `USER`.`TAG` = `OLD`.`TAG`;
END$$
DELIMITER ;

CREATE TABLE `musicbotdb`.`USER` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(45) NULL,
  `TAG` VARCHAR(45) NULL,
  `YTI_URL` VARCHAR(255) NULL,
  `UPDT_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
--  INDEX `FQ_MOOD_idx` (`TAG` ASC),
--  CONSTRAINT `FQ_MOOD`
--    FOREIGN KEY (`TAG`)
--    REFERENCES `musicbotdb`.`MOOD` (`TAG`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
DELIMITER $$
USE `musicbotdb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musicbotdb`.`USER_AFTER_DELETE` AFTER DELETE ON `USER` FOR EACH ROW
BEGIN
    DELETE FROM `USER_SONG` WHERE `USER_SONG`.`ID` = `OLD`.`ID`;
END$$
DELIMITER ;

CREATE TABLE `musicbotdb`.`USER_SONG` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `URL` VARCHAR(255) NOT NULL,
  `PLAY_COUNT` INT UNSIGNED NULL,
  `LAST_PLAYED_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `URL`)
--  INDEX `FQ_SONG_idx` (`URL` ASC),
--  CONSTRAINT `FQ_USER_SONG_USER`
--    FOREIGN KEY (`ID`)
--    REFERENCES `musicbotdb`.`USER` (`ID`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `FQ_USER_SONG_SONG`
--    FOREIGN KEY (`URL`)
--    REFERENCES `musicbotdb`.`SONG` (`URL`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `musicbotdb`.`MOOD_SONG` (
  `TAG` VARCHAR(45) NOT NULL,
  `URL` VARCHAR(255) NOT NULL,
  `LAST_PLAYED_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAG`, `URL`)
--  CONSTRAINT `FQ_MOOD_SONG_MOOD`
--    FOREIGN KEY (`TAG`)
--    REFERENCES `musicbotdb`.`MOOD` (`TAG`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `FQ_MOOD_SONG_SONG`
--    FOREIGN KEY (`URL`)
--    REFERENCES `musicbotdb`.`SONG` (`URL`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

CREATE TABLE `musicbotdb`.`EMAIL` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SUBJECT` VARCHAR(255) NULL,
  `CONTENTS` NVARCHAR(2000) NULL,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
