CREATE TABLE `musicbotdb`.`SONG` (
  `URL` VARCHAR(45) NOT NULL,
  `TITLE` VARCHAR(45) NULL,
  `PLAY_COUNT` INT UNSIGNED NULL,
  `VOLUME` INT(3) UNSIGNED NULL,
  `UPDT_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`URL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DELIMITER $$
USE `musicbotdb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musicbotdb`.`SONG_AFTER_DELETE` AFTER DELETE ON `SONG` FOR EACH ROW
BEGIN
    DELETE FROM `musicbotdb`.`USER_SONG` WHERE `URL` = OLD.URL;
    DELETE FROM `musicbotdb`.`MOOD_SONG` WHERE `URL` = OLD.URL;
END$$
DELIMITER ;

CREATE TABLE `musicbotdb`.`MOOD` (
  `TAG` VARCHAR(45) NOT NULL,
  `UPDT_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAG`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DELIMITER $$
USE `musicbotdb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musicbotdb`.`MOOD_AFTER_DELETE` AFTER DELETE ON `MOOD` FOR EACH ROW
BEGIN
    DELETE FROM `MOOD_SONG` WHERE `MOOD_SONG`.`MOOD_TAG` = `OLD`.`TAG`;
    UPDATE `USER` SET `MOOD_TAG` = NULL WHERE `USER`.`MOOD_TAG` = `OLD`.`TAG`;
END$$
DELIMITER ;

CREATE TABLE `musicbotdb`.`USER` (
  `ID` BIGINT UNSIGNED NOT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `MOOD_TAG` VARCHAR(45) NULL,
  `YTI_URL` VARCHAR(45) NULL,
  `UPDT_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
--  INDEX `FQ_MOOD_idx` (`MOOD_TAG` ASC),
--  CONSTRAINT `FQ_MOOD`
--    FOREIGN KEY (`MOOD_TAG`)
--    REFERENCES `musicbotdb`.`MOOD` (`TAG`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
DELIMITER $$
USE `musicbotdb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `musicbotdb`.`USER_AFTER_DELETE` AFTER DELETE ON `USER` FOR EACH ROW
BEGIN
    DELETE FROM USER_SONG WHERE ID = OLD.ID;
END$$
DELIMITER ;

CREATE TABLE `musicbotdb`.`USER_SONG` (
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `SONG_URL` VARCHAR(45) NOT NULL,
  `PLAY_COUNT` INT UNSIGNED NULL,
  `LAST_PLAYED_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`, `SONG_URL`)
--  INDEX `FQ_SONG_idx` (`SONG_URL` ASC),
--  CONSTRAINT `FQ_USER_SONG_USER`
--    FOREIGN KEY (`USER_ID`)
--    REFERENCES `musicbotdb`.`USER` (`ID`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `FQ_USER_SONG_SONG`
--    FOREIGN KEY (`SONG_URL`)
--    REFERENCES `musicbotdb`.`SONG` (`URL`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `musicbotdb`.`MOOD_SONG` (
  `MOOD_TAG` VARCHAR(45) NOT NULL,
  `SONG_URL` VARCHAR(45) NOT NULL,
  `PLAY_COUNT` INT UNSIGNED NULL,
  `LAST_PLAYED_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MOOD_TAG`, `SONG_URL`)
--  CONSTRAINT `FQ_MOOD_SONG_MOOD`
--    FOREIGN KEY (`MOOD_TAG`)
--    REFERENCES `musicbotdb`.`MOOD` (`TAG`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT `FQ_MOOD_SONG_SONG`
--    FOREIGN KEY (`SONG_URL`)
--    REFERENCES `musicbotdb`.`SONG` (`URL`)
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `musicbotdb`.`EMAIL` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SUBJECT` VARCHAR(45) NULL,
  `CONTENTS` NVARCHAR(2000) NULL,
  `CRET_DT_TM` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
